### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by mandyedi** [mandyedi/raytracing-from-the-ground-up#15]
# TODO
- [x] File groups - so folder structure remains in the IDE.
- [x] gtest_force_shared_crt - Make it automatically set when CMake is run
    Fixes the error: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'
    In CMakeCache.txt: gtest_force_shared_crt:BOOL=ON
    or
    In CMakeLists.txt: set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)  
- [x] Debug and release build

_CRT_SECURE_NO_WARNINGS - Define for MSVC
    In Visual Studio: Configuration Properties > C/C++ > Preprocessor > Preprocessor Definitions

# Good examples
- https://github.com/mmp/pbrt-v3/blob/master/CMakeLists.txt
- https://github.com/mmp/pbrt-v4/blob/master/CMakeLists.txt

**Comment by mandyedi** [comment]
Todos finished.
